FROM docker.io/fedora:43

RUN dnf install -y \
    nodejs \
    npm \
    libicu \
    git \
    && dnf clean all

RUN useradd -m node && \
    mkdir -p /app && \
    chown -R node:node /app

USER node
WORKDIR /app

EXPOSE 5173

ENTRYPOINT ["npm"]
CMD ["run", "dev", "--", "--host"]